In [43]:
import pandas as pd
import os

In [44]:
def process_data(data_txt):
    cols = ['MJD','R.A. (mas)', 'Dec. (mas)', 'Err. R.A. (mas)', 'Err. Dec. (mas)', 'Corr.', 'Del.']
    cols_widths = [(1,9),(10,26),(27,46),(47,56),(57,66),(67,74),(75,79)]
    df = pd.read_fwf(data_txt, colspecs=cols_widths, skiprows=4, header=None, names=cols)    
    df_new = df.apply(pd.to_numeric, errors='coerce').dropna()    
    return df_new

In [18]:
directory = 'series_ind_dem'
files = os.listdir(directory)

In [37]:
dfs = {}

In [38]:
for file in files:
    f = os.path.join(directory, filename)
    if file.endswith('.txt'):
        df = process_data(f)
        dfs[file] = df

In [40]:
dfs['2027-065_dem.txt']

,MJD,R.A. (mas),Dec. (mas),Err. R.A. (mas),Err. Dec. (mas),Corr.,Del.
0,3560.315,2.164104,0.803502,0.4775,0.8565,0.137,26
1,6875.043,0.000000,0.124801,0.2649,0.3237,0.282,64
2,7914.628,2.529243,-1.027800,0.1358,0.2514,-0.137,134
3,8382.002,0.617724,0.021600,0.1771,0.2605,0.024,97
4,8635.004,-0.804937,0.000000,0.2674,0.5735,0.121,91

In [42]:
process_data('series_ind_dem/2027-065_dem.txt')

,MJD,R.A. (mas),Dec. (mas),Err. R.A. (mas),Err. Dec. (mas),Corr.,Del.
0,4087.561,-3.353861,-4.314301,0.3502,0.5337,-0.289,61
1,7098.832,0.000000,1.773698,0.2431,0.4243,-0.020,81
2,7804.381,1.065577,1.405598,0.1529,0.3014,0.109,100
3,8203.797,1.325413,0.621202,0.3424,0.8989,-0.833,126
4,8593.332,0.536218,0.000000,0.2515,0.5612,-0.385,42

In [45]:
process_data('series_ind_dem/1803+784_dem.txt')

,MJD,R.A. (mas),Dec. (mas),Err. R.A. (mas),Err. Dec. (mas),Corr.,Del.
0,5754.258,-1.910705,-1.887599,1.2912,0.7417,-0.084,40
1,5759.251,-1.555439,-2.306200,1.2032,1.1362,0.028,19
2,5764.244,0.049960,1.459800,0.7069,0.6182,0.325,21
3,5769.259,-5.739611,0.890402,2.5316,1.1073,-0.363,25
4,5864.264,-2.973084,0.696002,0.6484,0.6307,0.547,27
...,...,...,...,...,...,...,...
2728,208.271,-0.031937,0.024700,0.1527,0.1679,0.070,89
2729,223.271,0.037455,-0.073901,0.1566,0.1349,-0.046,123
2730,230.270,0.184486,0.078800,0.1138,0.1303,0.272,93
2731,237.271,-0.296250,0.427201,0.1807,0.1814,0.002,82
2732,241.209,0.030198,0.267800,0.1769,0.2271,0.068,299