In [2]:
import numpy as np
import pandas as pd

In [3]:
# Load radio coordinate time series data
radiodata = pd.read_fwf('opa2023s.txt', header=None)

In [4]:
radiodata.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,SOU_LCO:,0000+212,96JAN02XV,EPOCH:,1996.00547,R:,00_03_19.35000207,-+,0.7320,D:,+21_29_44.5079098,-+,1.4364,Corr:,-0.7107,Obs:,31,/,135
1,SOU_LCO:,0000+212,96MAR13XV,EPOCH:,1996.19940,R:,00_03_19.35000722,-+,0.4109,D:,+21_29_44.5077080,-+,0.7789,Corr:,-0.2575,Obs:,35,/,83
2,SOU_LCO:,0000+212,17MAY27XC,EPOCH:,2017.40566,R:,00_03_19.35000261,-+,0.0830,D:,+21_29_44.5086277,-+,0.1453,Corr:,-0.1401,Obs:,135,/,135
3,SOU_LCO:,0000-160,15APR22XA,EPOCH:,2015.30801,R:,00_03_27.26417180,-+,0.1970,D:,-15_47_05.4563895,-+,0.4546,Corr:,-0.1534,Obs:,77,/,81
4,SOU_LCO:,0000-160,18JAN18XC,EPOCH:,2018.05081,R:,00_03_27.26416494,-+,0.3202,D:,-15_47_05.4551060,-+,0.7182,Corr:,-0.7745,Obs:,65,/,72

In [5]:
radiodata['OBS'] = radiodata[16].astype(str) + ' ' + radiodata[17] + ' ' + radiodata[18].astype(str)
radiodata = radiodata.drop(radiodata.columns[[0,3,5,7,9,11,13,15,16,17,18]], axis=1)
radiodata.head(5)

,1,2,4,6,8,10,12,14,OBS
0,0000+212,96JAN02XV,1996.00547,00_03_19.35000207,0.7320,+21_29_44.5079098,1.4364,-0.7107,31 / 135
1,0000+212,96MAR13XV,1996.19940,00_03_19.35000722,0.4109,+21_29_44.5077080,0.7789,-0.2575,35 / 83
2,0000+212,17MAY27XC,2017.40566,00_03_19.35000261,0.0830,+21_29_44.5086277,0.1453,-0.1401,135 / 135
3,0000-160,15APR22XA,2015.30801,00_03_27.26417180,0.1970,-15_47_05.4563895,0.4546,-0.1534,77 / 81
4,0000-160,18JAN18XC,2018.05081,00_03_27.26416494,0.3202,-15_47_05.4551060,0.7182,-0.7745,65 / 72

In [6]:
radiodata = radiodata.rename(columns={1: "SOU_LCO", 2: "DATETIME", 4: "EPOCH", 6: "RA", 8: "RA ERR", 10: "DEC", 12: "DEC ERR", 14: "CORR"})
radiodata.head(5)

,SOU_LCO,DATETIME,EPOCH,RA,RA ERR,DEC,DEC ERR,CORR,OBS
0,0000+212,96JAN02XV,1996.00547,00_03_19.35000207,0.7320,+21_29_44.5079098,1.4364,-0.7107,31 / 135
1,0000+212,96MAR13XV,1996.19940,00_03_19.35000722,0.4109,+21_29_44.5077080,0.7789,-0.2575,35 / 83
2,0000+212,17MAY27XC,2017.40566,00_03_19.35000261,0.0830,+21_29_44.5086277,0.1453,-0.1401,135 / 135
3,0000-160,15APR22XA,2015.30801,00_03_27.26417180,0.1970,-15_47_05.4563895,0.4546,-0.1534,77 / 81
4,0000-160,18JAN18XC,2018.05081,00_03_27.26416494,0.3202,-15_47_05.4551060,0.7182,-0.7745,65 / 72

Ekstrak data kumpulan epoch, RA, dan Dec dari setiap quasar berdasarkan nama quasarnya

In [7]:
sourcedata = {}
for source, df_source in radiodata.groupby('SOU_LCO'):
    sourcedata[str(source)] = df_source

In [8]:
sourcelist = list(sourcedata.keys())
sourcelist

['0000+212',
 '0000-160',
 '0000-197',
 '0000-199',
 '0001+459',
 '0001+478',
 '0001-120',
 '0002+051',
 '0002+200',
 '0002+541',
 '0002-170',
 '0002-350',
 '0002-478',
 '0003+123',
 '0003+158',
 '0003+340',
 '0003+380',
 '0003-066',
 '0003-302',
 '0004+240',
 '0005+101',
 '0005+114',
 '0005+568',
 '0005+683',
 '0005-239',
 '0005-262',
 '0006+061',
 '0006+06A',
 '0006+397',
 '0006+771',
 '0006-363',
 '0007+016',
 '0007+171',
 '0007+205',
 '0007+439',
 '0007+757',
 '0007-048',
 '0007-325',
 '0008+006',
 '0008+704',
 '0008-222',
 '0008-264',
 '0008-300',
 '0008-307',
 '0008-311',
 '0008-421',
 '0009+070',
 '0009+081',
 '0009+467',
 '0009+655',
 '0009-148',
 '0010+336',
 '0010+405',
 '0010+463',
 '0010-155',
 '0010-401',
 '0011+189',
 '0011-046',
 '0012+077',
 '0012+319',
 '0012+610',
 '0012-184',
 '0013-005',
 '0013-184',
 '0013-240',
 '0014+813',
 '0015+145',
 '0015+529',
 '0015-054',
 '0015-280',
 '0016+453',
 '0016+731',
 '0017+200',
 '0017+257',
 '0017+296',
 '0017-307',
 '0018+715',
 '0018+729',
 '0019+058',
 '0019+451',
 '0020+015',
 '0020+446',
 '0021+243',
 '0021+464',
 '0021-084',
 '0022+390',
 '0022-044',
 '0022-227',
 '0022-423',
 '0023+083',
 '0023-263',
 '0023-354',
 '0024+092',
 '0024+224',
 '0024+597',
 '0024-114',
 '0025+197',
 '0025+449',
 '0026+048',
 '0026+076',
 '0026+324',
 '0026+346',
 '0026-015',
 '0027+056',
 '0027+703',
 '0027-024',
 '0027-426',
 '0028-137',
 '0028-396',
 '0029-147',
 '0029-414',
 '0030+196',
 '0031+211',
 '0031-040',
 '0032+276',
 '0032+612',
 '0032-011',
 '0033+098',
 '0033+142',
 '0033+143',
 '0033-088',
 '0034+078',
 '0034+108',
 '0034+214',
 '0034+393',
 '0034-014',
 '0034-220',
 '0035+121',
 '0035+186',
 '0035+238',
 '0035+367',
 '0035+413',
 '0035+503',
 '0035-024',
 '0035-037',
 '0035-252',
 '0035-340',
 '0035-534',
 '0036-099',
 '0036-191',
 '0036-216',
 '0037+011',
 '0037+094',
 '0037+139',
 '0037+487',
 '0037-329',
 '0037-593',
 '0038+133',
 '0038+319',
 '0038-019',
 '0038-020',
 '0038-326',
 '0039+230',
 '0039+568',
 '0039-407',
 '0040+098',
 '0041+047',
 '0041+677',
 '0042+186',
 '0042-373',
 '0043+246',
 '0043-268',
 '0043-392',
 '0044+030',
 '0044+387',
 '0044+566',
 '0044-846',
 '0045+243',
 '0046+063',
 '0046+511',
 '0046+861',
 '0046-315',
 '0047+023',
 '0047-051',
 '0047-579',
 '0048+447',
 '0048-071',
 '0048-097',
 '0048-427',
 '0049+003',
 '0049+162',
 '0049+437',
 '0050-287',
 '0051+291',
 '0051+679',
 '0051+706',
 '0051-077',
 '0052-125',
 '0052-201',
 '0054+078',
 '0054+161',
 '0054-006',
 '0055+060',
 '0055+329',
 '0055-016',
 '0055-059',
 '0055-328',
 '0055-340',
 '0056+579',
 '0056-001',
 '0056-572',
 '0057+334',
 '0057+678',
 '0057-338',
 '0058+058',
 '0058+498',
 '0059+163',
 '0059+581',
 '0059-287',
 '0100+151',
 '0100-270',
 '0100-760',
 '0101+113',
 '0101-126',
 '0102+480',
 '0102+511',
 '0102-245',
 '0103+057',
 '0103+127',
 '0103+253',
 '0103+337',
 '0103-021',
 '0104+195',
 '0104-035',
 '0104-275',
 '0104-408',
 '0105+129',
 '0105+259',
 '0105-008',
 '0105-222',
 '0106+013',
 '0106+315',
 '0106+612',
 '0106+678',
 '0107+069',
 '0107+562',
 '0107-025',
 '0107-045',
 '0107-610',
 '0108+388',
 '0108-079',
 '0108-170',
 '0109+026',
 '0109+200',
 '0109+224',
 '0109+351',
 '0109-135',
 '0110+318',
 '0110+495',
 '0110-361',
 '0110-668',
 '0111+021',
 '0111+131',
 '0112+131',
 '0112+13A',
 '0112-017',
 '0112-245',
 '0113+241',
 '0113-118',
 '0113-283',
 '0113-310',
 '0114+140',
 '0114-211',
 '0115-214',
 '0116+082',
 '0116+319',
 '0116-219',
 '0117-171',
 '0118+111',
 '0118-272',
 '0118-283',
 '0119+041',
 '0119+115',
 '0119+247',
 '0119+296',
 '0119-005',
 '0119-011',
 '0119-046',
 '0120+137',
 '0120+259',
 '0120+304',
 '0121+560',
 '0121-040',
 '0121-096',
 '0122+278',
 '0122+470',
 '0122+705',
 '0122-003',
 '0122-260',
 '0122-345',
 '0122-514',
 '0123+257',
 '0123+731',
 '0123-226',
 '0124-086',
 '0124-155',
 '0125+487',
 '0125+628',
 '0125-484',
 '0127+084',
 '0127+145',
 '0128+383',
 '0129+220',
 '0129+431',
 '0129+560',
 '0130+242',
 '0130+691',
 '0130-171',
 '0130-447',
 '0131-001',
 '0131-522',
 '0132-389',
 '0133+476',
 '0133-204',
 '0134+215',
 '0134+311',
 '0135+091',
 '0135-247',
 '0135-274',
 '0136+176',
 '0136-059',
 '0136-231',
 '0137+012',
 '0137+434',
 '0137+467',
 '0137+635',
 '0137-158',
 '0137-240',
 '0138-097',
 '0139-022',
 '0139-097',
 '0140+120',
 '0140+412',
 '0140+490',
 '0140-274',
 '0140-322',
 '0141+268',
 '0141+579',
 '0142-278',
 '0142-398',
 '0143+230',
 '0144+209',
 '0144+487',
 '0144+584',
 '0145+210',
 '0145+386',
 '0145+420',
 '0146+056',
 '0147+187',
 '0147+265',
 '0147-076',
 '0148+250',
 '0148+274',
 '0148-177',
 '0149+218',
 '0149+335',
 '0149+370',
 '0149+710',
 '0149-175',
 '0149-348',
 '0150+000',
 '0150+015',
 '0150-144',
 '0150-193',
 '0150-299',
 '0150-334',
 '0151+081',
 '0151+109',
 '0151+474',
 '0152+043',
 '0153+222',
 '0153+389',
 '0153+744',
 '0153-410',
 '0154-000',
 '0155+211',
 '0155-10A',
 '0155-549',
 '0156+128',
 '0156+166',
 '0156-144',
 '0157+808',
 '0158+031',
 '0158-141',
 '0158-159',
 '0159+034',
 '0159+418',
 '0159+723',
 '0159+839',
 '0159+870',
 '0159-062',
 '0159-117',
 '0159-200',
 '0159-668',
 '0200+304',
 '0200+30A',
 '0200+539',
 '0200+751',
 '0201+023',
 '0201+088',
 '0201+113',
 '0201+365',
 '0201+398',
 '0201+438',
 '0202+145',
 '0202+149',
 '0202+240',
 '0202+319',
 '0202-172',
 '0202-337',
 '0202-765',
 '0203+625',
 '0203-120',
 '0203-349',
 '0204+316',
 '0204-224',
 '0205+643',
 '0205+722',
 '0205-010',
 '0206+136',
 '0206+293',
 '0206-048',
 '0206-178',
 '0206-270',
 '0206-625',
 '0206-689',
 '0207+507',
 '0207-078',
 '0207-149',
 '0208+040',
 '0208+106',
 '0208-512',
 '0209+168',
 '0209-162',
 '0209-204',
 '0210+119',
 '0210+181',
 '0210+225',
 '0210+366',
 '0210+515',
 '0210-075',
 '0210-180',
 '0211+171',
 '0212+735',
 '0212-039',
 '0212-620',
 '0213+051',
 '0213+432',
 '0213+443',
 '0213-013',
 '0213-015',
 '0213-026',
 '0214+083',
 '0214-085',
 '0214-105',
 '0214-330',
 '0214-522',
 '0215+015',
 '0215-015',
 '0215-167',
 '0216+011',
 '0216+472',
 '0216+478',
 '0217+166',
 '0217+324',
 '0217-189',
 '0218+095',
 '0218-132',
 '0218-133',
 '0218-220',
 '0219+096',
 '0219+428',
 '0219+628',
 '0219-164',
 '0219-474',
 '0219-637',
 '0220-023',
 '0220-349',
 '0221+067',
 '0221-171',
 '0221-540',
 '0222+185',
 '0222+296',
 '0222+310',
 '0222-234',
 '0223+113',
 '0223+341',
 '0224+498',
 '0224+540',
 '0224-189',
 '0225+419',
 '0225-306',
 '0226-038',
 '0226-375',
 '0226-559',
 '0227+403',
 '0227+448',
 '0227-369',
 '0227-542',
 '0228-163',
 '0229+072',
 '0229+131',
 '0229+230',
 '0229+262',
 '0229-398',
 '0229-479',
 '0230+344',
 '0230-288',
 '0230-790',
 '0231+045',
 '0232-042',
 '0233-133',
 '0234+052',
 '0234+285',
 '0234+301',
 '0234+469',
 '0234-301',
 '0235+164',
 '0235+205',
 '0235-266',
 '0235-618',
 '0236+420',
 '0237+040',
 '0237+185',
 '0237-027',
 '0237-233',
 '0238+711',
 '0238-052',
 '0239+108',
 '0239+175',
 '0240+110',
 '0240-060',
 '0240-217',
 '0241+622',
 '0241-564',
 '0242+131',
 '0242+238',
 '0242-113',
 '0243+339',
 '0243+354',
 '0244+327',
 '0244-128',
 '0244-297',
 '0244-452',
 '0244-470',
 '0245+043',
 '0245-167',
 '0246+061',
 '0248+373',
 '0248+430',
 '0248+560',
 '0248-266',
 '0249+171',
 '0249+383',
 '0250+178',
 '0250+320',
 '0250+508',
 '0250-001',
 '0250-122',
 '0250-225',
 '0251+235',
 '0251+393',
 '0251+785',
 '0252+657',
 '0252-549',
 '0252-712',
 '0253+133',
 '0253-218',
 '0254+185',
 '0254+434',
 '0254-334',
 '0255+288',
 '0255-124',
 '0256+054',
 '0256+075',
 '0256+115',
 '0256+192',
 '0256+423',
 '0256-005',
 '0256-256',
 '0256-393',
 '0257-057',
 '0258+011',
 '0258+058',
 '0258+533',
 '0258+772',
 '0258-163',
 '0258-170',
 '0258-184',
 '0259+121',
 '0259+203',
 '0259+681',
 '0259-316',
 '0300+470',
 '0301+336',
 '0301-243',
 '0302+173',
 '0302+625',
 '0302-437',
 '0302-623',
 '0303+051',
 '0303+130',
 '0303-245',
 '0304+124',
 '0305+237',
 '0305-491',
 '0306+102',
 '0306+274',
 '0306-061',
 '0307+380',
 '0307-085',
 '0307-362',
 '0308-611',
 '0309+360',
 '0309+411',
 '0310+013',
 '0310+022',
 '0310+410',
 '0312+100',
 '0312-770',
 '0313-020',
 '0313-171',
 '0314+565',
 '0314+696',
 '0315+291',
 '0315+389',
 '0315-006',
 '0315-282',
 '0316+159',
 '0316+308',
 '0316-164',
 '0316-444',
 '0317+188',
 '0317+659',
 '0318+438',
 '0318-172',
 '0319+121',
 '0319+396',
 '0319-056',
 '0319-133',
 '0319-315',
 '0320+015',
 '0320+045',
 '0321+340',
 '0321+467',
 '0322+222',
 '0322-230',
 '0322-294',
 '0323-244',
 '0324-328',
 '0324-379',
 '0325+005',
 '0325+256',
 '0325+395',
 '0325-182',
 '0325-222',
 '0326+278',
 '0326+349',
 '0327+364',
 '0327+467',
 '0327-241',
 '0328+238',
 '0329+654',
 '0329-110',
 '0329-255',
 '0329-404',
 '0331+022',
 '0332+078',
 '0332-375',
 '0332-403',
 '0333-073',
 '0334+014',
 '0334+309',
 '0334-131',
 '0334-207',
 '0334-546',
 '0335+599',
 '0335-122',
 '0335-364',
 '0336+133',
 '0336+473',
 '0336+539',
 '0336-017',
 '0337+337',
 '0338+388',
 '0338+480',
 '0338-030',
 '0338-214',
 '0339+131',
 '0339+683',
 '0340+362',
 '0340-140',
 '0340-302',
 '0341+065',
 '0341+158',
 '0341+729',
 '0341-256',
 '0342+147',
 '0342+538',
 '0343+485',
 '0344+199',
 '0344+235',
 '0344+558',
 '0345+085',
 '0345+416',
 '0345+460',
 '0346+209',
 '0346+514',
 '0346+800',
 '0346-163',
 '0346-279',
 '0347-211',
 '0348+049',
 '0348-031',
 '0348-120',
 '0348-326',
 '0349+662',
 '0350+177',
 '0350+465',
 '0350-253',
 '0351+045',
 '0351+390',
 '0352+123',
 '0352+605',
 '0352-164',
 '0353+289',
 '0354+000',
 '0354+231',
 '0354+559',
 '0354+599',
 '0354-405',
 '0355+055',
 '0355-079',
 '0355-483',
 '0355-669',
 '0356+278',
 '0356+322',
 '0356-033',
 '0357+057',
 '0357-263',
 '0358+040',
 '0358+210',
 '0358-162',
 '0359-151',
 '0359-294',
 '0400+258',
 '0400-319',
 '0402+379',
 '0402+682',
 '0402-362',
 '0403+064',
 '0403+768',
 '0403-132',
 '0403-179',
 '0404+065',
 '0404+075',
 '0404-240',
 '0405+305',
 '0405-015',
 '0405-123',
 '0405-331',
 '0405-385',
 '0406+065',
 '0406+121',
 '0406-056',
 '0406-127',
 '0407-170',
 '0407-199',
 '0407-658',
 '0408+085',
 '0409+000',
 '0409+045',
 '0409+188',
 '0409+229',
 '0409+527',
 '0409-280',
 '0410+110',
 '0411+054',
 '0411+341',
 '0411-063',
 '0412+447',
 '0413-136',
 '0413-210',
 '0414+548',
 '0414-157',
 '0414-189',
 '0414-253',
 '0414-337',
 '0414-341',
 '0415+211',
 '0415+379',
 '0415+398',
 '0415+572',
 '0416-216',
 '0417-302',
 '0418+437',
 '0418+532',
 '0418-151',
 '0419+308',
 '0419-068',
 '0420+022',
 '0420+210',
 '0420+417',
 '0420-014',
 '0420-206',
 '0421+019',
 '0421+023',
 '0421+145',
 '0421+464',
 '0421+683',
 '0422+004',
 '0422+079',
 '0422+224',
 '0422-380',
 '0422-389',
 '0423+051',
 '0423+183',
 '0423+233',
 '0423+237',
 '0423+297',
 '0423-163',
 '0424+328',
 '0424+414',
 '0424-131',
 '0425+048',
 '0425+174',
 '0425-071',
 '0426+181',
 '0426+273',
 '0426+332',
 '0426-126',
 '0426-380',
 '0427-055',
 '0427-230',
 '0427-502',
 '0428+205',
 '0428+314',
 '0428-042',
 '0428-252',
 '0429+174',
 '0429+448',
 '0430+289',
 '0430-163',
 '0430-332',
 '0431-512',
 '0432+254',
 '0432-148',
 '0432-253',
 '0432-606',
 '0433+295',
 '0433-101',
 '0433-422',
 '0434+299',
 '0434-188',
 '0434-240',
 '0435+217',
 '0435-300',
 '0436+052',
 '0436+306',
 '0436+426',
 '0436-089',
 '0436-129',
 '0436-203',
 '0437+145',
 '0437+273',
 '0437-303',
 '0437-454',
 '0437-719',
 '0438+040',
 '0438+785',
 '0438-436',
 '0439+186',
 '0439+283',
 '0439-299',
 '0439-337',
 '0440+209',
 '0440+345',
 '0440-285',
 '0440-520',
 '0441+106',
 '0441-699',
 '0442+071',
 '0442+389',
 '0443+592',
 '0444+634',
 '0445+097',
 '0445+364',
 '0445-221',
 '0446+112',
 '0446+113',
 '0446+178',
 '0446+462',
 '0446+595',
 '0446-096',
 '0446-212',
 '0446-265',
 '0447+227',
 '0447+408',
 '0447-010',
 '0448-187',
 '0448-392',
 '0449+125',
 '0450+013',
 '0450+299',
 '0450-743',
 '0451-078',
 '0451-282',
 '0451-398',
 '0452+068',
 '0453+269',
 '0454+039',
 '0454+066',
 '0454+291',
 '0454+550',
 '0454+844',
 '0454-088',
 '0454-220',
 '0454-234',
 '0454-463',
 '0454-810',
 '0455+201',
 '0455-183',
 '0456+060',
 '0456+310',
 '0456+428',
 '0456+714',
 '0457+024',
 '0458+138',
 '0458-020',
 '0459+060',
 '0459+135',
 '0459+252',
 '0459+387',
 '0459+415',
 '0459-139',
 '0500+019',
 '0500+339',
 '0500+443',
 '0500-357',
 '0501+279',
 '0501-067',
 '0501-215',
 '0502+041',
 '0502+049',
 '0502-152',
 '0503+216',
 '0503+466',
 '0503+608',
 '0503-043',
 '0503-163',
 '0503-608',
 '0504-099',
 '0505+354',
 '0506+056',
 '0506+101',
 '0506+398',
 '0506-196',
 '0506-332',
 '0506-612',
 '0507+179',
 '0507-611',
 '0508+138',
 '0508+264',
 '0508-317',
 '0509+011',
 '0509+152',
 '0509+205',
 '0509+293',
 '0509+406',
 '0510+559',
 '0510-005',
 '0511+009',
 '0511-203',
 '0511-220',
 '0512-205',
 '0513+276',
 '0513+455',
 '0513-459',
 '0514+074',
 '0514+109',
 '0514+330',
 '0514+474',
 '0514-156',
 '0514-161',
 '0514-459',
 '0515+067',
 '0515+208',
 '0515+227',
 '0515-053',
 '0515-179',
 '0516+087',
 '0516-095',
 '0516-249',
 '0516-340',
 '0516-621',
 '0517-027',
 '0517-726',
 '0518+211',
 '0518+600',
 '0518+705',
 ...]

In [9]:
sourcedata['0227+448']

,SOU_LCO,DATETIME,EPOCH,RA,RA ERR,DEC,DEC ERR,CORR,OBS
32022,0227+448,19APR29XB,2019.32706,02_30_49.91933012,0.7318,+45_02_07.4922444,0.5926,0.3453,42 / 56

In [10]:
len(sourcedata)

4617

In [11]:
sourcedata['1803+784']

,SOU_LCO,DATETIME,EPOCH,RA,RA ERR,DEC,DEC ERR,CORR,OBS
212978,1803+784,82JUN17X,1982.46218,18_00_45.68405113,2.8209,+78_28_04.0168253,0.7389,-0.3476,11 / 19
212979,1803+784,83MAY05X,1983.34460,18_00_45.68395303,0.9008,+78_28_04.0184133,0.1784,-0.0897,75 / 156
212980,1803+784,83MAY11X,1983.35887,18_00_45.68442706,4.9180,+78_28_04.0169464,1.2485,-0.4544,7 / 7
212981,1803+784,84JAN25X,1984.06927,18_00_45.68393330,2.9472,+78_28_04.0184736,0.6814,-0.3781,24 / 24
212982,1803+784,84FEB08X,1984.10743,18_00_45.68404837,3.4165,+78_28_04.0182602,0.5626,-0.3493,15 / 16
...,...,...,...,...,...,...,...,...,...
216022,1803+784,22DEC01XE,2022.91929,18_00_45.68388825,0.1758,+78_28_04.0183446,0.0374,-0.0334,216 / 218
216023,1803+784,22DEC08XE,2022.93845,18_00_45.68393881,0.2145,+78_28_04.0183665,0.0483,-0.0400,214 / 221
216024,1803+784,22DEC12XA,2022.94923,18_00_45.68390370,0.1996,+78_28_04.0183079,0.0416,-0.0072,318 / 342
216025,1803+784,22DEC14XE,2022.95488,18_00_45.68391285,0.2598,+78_28_04.0183327,0.0609,0.0628,145 / 165
216026,1803+784,22DEC21XE,2022.97405,18_00_45.68388250,0.1896,+78_28_04.0183676,0.0371,-0.0396,276 / 290