In [3]:
import numpy as np
import pandas as pd

In [4]:
# Load radio coordinate time series data
radiodata = pd.read_fwf('opa2023r.txt', header=None)

In [5]:
radiodata.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,SOU_LCO:,0000+019,19JAN27XC,EPOCH:,2019.07415,R:,00_03_14.96282951,-+,0.2109,D:,+02_14_57.4835870,-+,0.5318,Corr:,-0.3702,Obs:,108.0,/,135.0
1,SOU_LCO:,0000+019,19JUL05XC,EPOCH:,2019.51020,R:,00_03_14.96269267,-+,0.3585,D:,+02_14_57.4865342,-+,0.7225,Corr:,-0.5874,Obs:,76.0,/,84.0
2,SOU_LCO:,0000+212,96JAN02XV,EPOCH:,1996.00547,R:,00_03_19.34997151,-+,0.7600,D:,+21_29_44.5070773,-+,1.4591,Corr:,-0.6595,Obs:,31.0,/,135.0
3,SOU_LCO:,0000+212,96MAR13XV,EPOCH:,1996.19940,R:,00_03_19.34997879,-+,0.6409,D:,+21_29_44.5090913,-+,0.9638,Corr:,-0.4648,Obs:,35.0,/,83.0
4,SOU_LCO:,0000+212,15JAN23XC,EPOCH:,2015.06491,R:,00_03_19.35000429,-+,0.1928,D:,+21_29_44.5077865,-+,0.2793,Corr:,0.1283,Obs:,96.0,/,111.0

In [6]:
radiodata['OBS'] = radiodata[16].astype(str) + ' ' + radiodata[17] + ' ' + radiodata[18].astype(str)
radiodata = radiodata.drop(radiodata.columns[[0,3,5,7,9,11,13,15,16,17,18]], axis=1)
radiodata.head(5)

,1,2,4,6,8,10,12,14,OBS
0,0000+019,19JAN27XC,2019.07415,00_03_14.96282951,0.2109,+02_14_57.4835870,0.5318,-0.3702,108.0 / 135.0
1,0000+019,19JUL05XC,2019.51020,00_03_14.96269267,0.3585,+02_14_57.4865342,0.7225,-0.5874,76.0 / 84.0
2,0000+212,96JAN02XV,1996.00547,00_03_19.34997151,0.7600,+21_29_44.5070773,1.4591,-0.6595,31.0 / 135.0
3,0000+212,96MAR13XV,1996.19940,00_03_19.34997879,0.6409,+21_29_44.5090913,0.9638,-0.4648,35.0 / 83.0
4,0000+212,15JAN23XC,2015.06491,00_03_19.35000429,0.1928,+21_29_44.5077865,0.2793,0.1283,96.0 / 111.0

In [7]:
radiodata = radiodata.rename(columns={1: "SOU_LCO", 2: "DATETIME", 4: "EPOCH", 6: "RA", 8: "RA ERR", 10: "DEC", 12: "DEC ERR", 14: "CORR"})
radiodata.head(5)

,SOU_LCO,DATETIME,EPOCH,RA,RA ERR,DEC,DEC ERR,CORR,OBS
0,0000+019,19JAN27XC,2019.07415,00_03_14.96282951,0.2109,+02_14_57.4835870,0.5318,-0.3702,108.0 / 135.0
1,0000+019,19JUL05XC,2019.51020,00_03_14.96269267,0.3585,+02_14_57.4865342,0.7225,-0.5874,76.0 / 84.0
2,0000+212,96JAN02XV,1996.00547,00_03_19.34997151,0.7600,+21_29_44.5070773,1.4591,-0.6595,31.0 / 135.0
3,0000+212,96MAR13XV,1996.19940,00_03_19.34997879,0.6409,+21_29_44.5090913,0.9638,-0.4648,35.0 / 83.0
4,0000+212,15JAN23XC,2015.06491,00_03_19.35000429,0.1928,+21_29_44.5077865,0.2793,0.1283,96.0 / 111.0

Ekstrak data kumpulan epoch, RA, dan Dec dari setiap quasar berdasarkan nama quasarnya

In [8]:
sourcedata = {}
for source, df_source in radiodata.groupby('SOU_LCO'):
    sourcedata[str(source)] = df_source

In [9]:
sourcelist = list(sourcedata.keys())
sourcelist

['0000+019',
 '0000+212',
 '0000-006',
 '0000-160',
 '0000-197',
 '0000-199',
 '0001+459',
 '0001+478',
 '0001-120',
 '0002+051',
 '0002+200',
 '0002+541',
 '0002-018',
 '0002-170',
 '0002-350',
 '0002-478',
 '0003+123',
 '0003+158',
 '0003+340',
 '0003+380',
 '0003-066',
 '0003-302',
 '0004+240',
 '0005+021',
 '0005+101',
 '0005+114',
 '0005+568',
 '0005+683',
 '0005-239',
 '0005-262',
 '0006+061',
 '0006+06A',
 '0006+397',
 '0006+771',
 '0006-363',
 '0007+016',
 '0007+171',
 '0007+205',
 '0007+439',
 '0007+757',
 '0007-048',
 '0007-325',
 '0008+006',
 '0008+704',
 '0008-222',
 '0008-264',
 '0008-300',
 '0008-307',
 '0008-311',
 '0008-421',
 '0009+070',
 '0009+081',
 '0009+467',
 '0009+655',
 '0009-148',
 '0010+336',
 '0010+405',
 '0010+463',
 '0010-155',
 '0010-401',
 '0011+189',
 '0011-046',
 '0012+077',
 '0012+319',
 '0012+610',
 '0012-008',
 '0012-184',
 '0013-005',
 '0013-184',
 '0013-240',
 '0014+813',
 '0015+145',
 '0015+529',
 '0015-028',
 '0015-054',
 '0015-280',
 '0016+039',
 '0016+453',
 '0016+731',
 '0016-013',
 '0016-223',
 '0017+200',
 '0017+257',
 '0017+296',
 '0017-307',
 '0018+715',
 '0018+729',
 '0019+058',
 '0019+451',
 '0020+015',
 '0020+446',
 '0021+040',
 '0021+243',
 '0021+464',
 '0021-084',
 '0022+390',
 '0022-044',
 '0022-227',
 '0022-423',
 '0023+083',
 '0023-263',
 '0023-354',
 '0024+092',
 '0024+224',
 '0024+597',
 '0024-114',
 '0025+197',
 '0025+449',
 '0026+048',
 '0026+076',
 '0026+324',
 '0026+346',
 '0026-015',
 '0027+056',
 '0027+05A',
 '0027+587',
 '0027+703',
 '0027-024',
 '0027-426',
 '0028-017',
 '0028-137',
 '0028-396',
 '0029-147',
 '0029-414',
 '0030+048',
 '0030+196',
 '0031+211',
 '0031-040',
 '0032+276',
 '0032+612',
 '0032-011',
 '0033+079',
 '0033+082',
 '0033+098',
 '0033+142',
 '0033+143',
 '0033-088',
 '0034+078',
 '0034+108',
 '0034+214',
 '0034+393',
 '0034-014',
 '0034-220',
 '0035+121',
 '0035+186',
 '0035+238',
 '0035+367',
 '0035+413',
 '0035+503',
 '0035-024',
 '0035-037',
 '0035-252',
 '0035-340',
 '0035-534',
 '0036-099',
 '0036-191',
 '0036-216',
 '0037+011',
 '0037+094',
 '0037+139',
 '0037+487',
 '0037-329',
 '0037-593',
 '0038+133',
 '0038+319',
 '0038-019',
 '0038-020',
 '0038-326',
 '0039+211',
 '0039+230',
 '0039+568',
 '0039-407',
 '0040+098',
 '0041+047',
 '0041+677',
 '0042+186',
 '0042+456',
 '0042-373',
 '0043+044',
 '0043+246',
 '0043-268',
 '0043-392',
 '0044+030',
 '0044+085',
 '0044+387',
 '0044+566',
 '0044-846',
 '0045+079',
 '0045+243',
 '0045-000',
 '0046+063',
 '0046+511',
 '0046+861',
 '0046-315',
 '0047+023',
 '0047-051',
 '0047-579',
 '0048+447',
 '0048-071',
 '0048-097',
 '0048-427',
 '0049+003',
 '0049+162',
 '0049+437',
 '0050-287',
 '0051+291',
 '0051+679',
 '0051+706',
 '0051-077',
 '0052+044',
 '0052+076',
 '0052-125',
 '0052-201',
 '0054+078',
 '0054+161',
 '0054-006',
 '0055+032',
 '0055+040',
 '0055+060',
 '0055+329',
 '0055-016',
 '0055-059',
 '0055-328',
 '0055-340',
 '0056+579',
 '0056-001',
 '0056-187',
 '0056-572',
 '0057+028',
 '0057+334',
 '0057+678',
 '0057-338',
 '0058+058',
 '0058+498',
 '0059+163',
 '0059+581',
 '0059-287',
 '0100+151',
 '0100-270',
 '0100-760',
 '0101+113',
 '0101-126',
 '0102+480',
 '0102+511',
 '0102-245',
 '0103+057',
 '0103+127',
 '0103+253',
 '0103+337',
 '0103-021',
 '0104+195',
 '0104-035',
 '0104-275',
 '0104-408',
 '0105+129',
 '0105+259',
 '0105-008',
 '0105-222',
 '0106+013',
 '0106+077',
 '0106+130',
 '0106+315',
 '0106+612',
 '0106+678',
 '0106-391',
 '0107+069',
 '0107+562',
 '0107-025',
 '0107-045',
 '0107-610',
 '0108+388',
 '0108-079',
 '0108-146',
 '0108-170',
 '0109+026',
 '0109+200',
 '0109+224',
 '0109+351',
 '0109-135',
 '0110+318',
 '0110+495',
 '0110-361',
 '0110-668',
 '0111+021',
 '0111+131',
 '0112+131',
 '0112+13A',
 '0112-017',
 '0112-245',
 '0113+241',
 '0113-118',
 '0113-283',
 '0113-310',
 '0114+074',
 '0114+140',
 '0114-211',
 '0115+027',
 '0115-214',
 '0116+082',
 '0116+319',
 '0116-219',
 '0117+117',
 '0117-171',
 '0118+111',
 '0118-272',
 '0118-283',
 '0119+041',
 '0119+097',
 '0119+115',
 '0119+247',
 '0119+296',
 '0119-005',
 '0119-011',
 '0119-046',
 '0120+137',
 '0120+259',
 '0120+304',
 '0121+560',
 '0121-040',
 '0121-096',
 '0122+278',
 '0122+470',
 '0122+705',
 '0122-003',
 '0122-260',
 '0122-345',
 '0122-514',
 '0123+257',
 '0123+731',
 '0123-015',
 '0123-048',
 '0123-226',
 '0124+125',
 '0124-086',
 '0124-155',
 '0125+487',
 '0125+628',
 '0125-176',
 '0125-484',
 '0127+077',
 '0127+084',
 '0127+145',
 '0128+383',
 '0129+220',
 '0129+431',
 '0129+560',
 '0130+242',
 '0130+691',
 '0130-083',
 '0130-171',
 '0130-447',
 '0131-001',
 '0131-522',
 '0132-389',
 '0133+476',
 '0133-204',
 '0133-410',
 '0134+084',
 '0134+215',
 '0134+311',
 '0135+091',
 '0135-247',
 '0135-274',
 '0136+176',
 '0136-059',
 '0136-231',
 '0137+012',
 '0137+081',
 '0137+434',
 '0137+467',
 '0137+635',
 '0137-158',
 '0137-240',
 '0137-273',
 '0138+136',
 '0138-097',
 '0138-381',
 '0139-022',
 '0139-097',
 '0140+120',
 '0140+412',
 '0140+490',
 '0140-274',
 '0140-322',
 '0141+268',
 '0141+339',
 '0141+579',
 '0142+127',
 '0142-278',
 '0142-398',
 '0143+230',
 '0144+209',
 '0144+487',
 '0144+584',
 '0145+102',
 '0145+210',
 '0145+386',
 '0145+420',
 '0146+056',
 '0146+092',
 '0147+187',
 '0147+265',
 '0147-076',
 '0148+250',
 '0148+274',
 '0148+546',
 '0148-177',
 '0149+082',
 '0149+120',
 '0149+218',
 '0149+335',
 '0149+370',
 '0149+710',
 '0149-175',
 '0149-348',
 '0150+000',
 '0150+015',
 '0150-144',
 '0150-193',
 '0150-299',
 '0150-334',
 '0151+081',
 '0151+109',
 '0151+474',
 '0152+043',
 '0153+222',
 '0153+389',
 '0153+744',
 '0153-149',
 '0153-410',
 '0154+410',
 '0154-000',
 '0154-244',
 '0155+211',
 '0155+810',
 '0155-10A',
 '0155-549',
 '0156+128',
 '0156+166',
 '0156-144',
 '0157+808',
 '0158+031',
 '0158-141',
 '0158-159',
 '0158-404',
 '0159+034',
 '0159+418',
 '0159+723',
 '0159+839',
 '0159+870',
 '0159-062',
 '0159-117',
 '0159-200',
 '0159-668',
 '0200+304',
 '0200+30A',
 '0200+539',
 '0200+751',
 '0201+023',
 '0201+088',
 '0201+113',
 '0201+365',
 '0201+398',
 '0201+438',
 '0201-440',
 '0202+145',
 '0202+149',
 '0202+240',
 '0202+319',
 '0202-172',
 '0202-337',
 '0202-765',
 '0203+625',
 '0203-120',
 '0203-349',
 '0204+316',
 '0204-224',
 '0205+080',
 '0205+643',
 '0205+722',
 '0205-010',
 '0205-242',
 '0205-391',
 '0206+136',
 '0206+293',
 '0206-048',
 '0206-178',
 '0206-270',
 '0206-625',
 '0206-689',
 '0207+079',
 '0207+507',
 '0207-078',
 '0207-149',
 '0208+040',
 '0208+106',
 '0208-512',
 '0209+138',
 '0209+168',
 '0209-162',
 '0209-204',
 '0210+119',
 '0210+181',
 '0210+225',
 '0210+366',
 '0210+515',
 '0210-075',
 '0210-180',
 '0211+091',
 '0211+171',
 '0212+735',
 '0212-039',
 '0212-214',
 '0212-620',
 '0213+051',
 '0213+432',
 '0213+443',
 '0213-013',
 '0213-015',
 '0213-026',
 '0214+083',
 '0214+108',
 '0214-085',
 '0214-105',
 '0214-330',
 '0214-522',
 '0215+015',
 '0215-015',
 '0215-167',
 '0216+011',
 '0216+472',
 '0216+478',
 '0217+166',
 '0217+324',
 '0217-189',
 '0218+095',
 '0218-132',
 '0218-133',
 '0218-220',
 '0219+096',
 '0219+428',
 '0219+628',
 '0219-164',
 '0219-474',
 '0219-637',
 '0220-023',
 '0220-349',
 '0221+067',
 '0221+137',
 '0221+177',
 '0221-171',
 '0221-540',
 '0222+185',
 '0222+296',
 '0222+310',
 '0222-234',
 '0222-262',
 '0223+093',
 '0223+113',
 '0223+341',
 '0223+814',
 '0224+176',
 '0224+498',
 '0224+540',
 '0224-189',
 '0225+419',
 '0225-306',
 '0226-038',
 '0226-375',
 '0226-559',
 '0227+403',
 '0227+448',
 '0227-369',
 '0227-542',
 '0228+626',
 '0228-163',
 '0229+072',
 '0229+131',
 '0229+200',
 '0229+230',
 '0229+262',
 '0229-398',
 '0229-479',
 '0230+344',
 '0230-288',
 '0230-790',
 '0231+045',
 '0231+183',
 '0231+620',
 '0232-042',
 '0233+128',
 '0233+160',
 '0233+434',
 '0233-133',
 '0234+052',
 '0234+110',
 '0234+285',
 '0234+301',
 '0234+469',
 '0234-301',
 '0235+091',
 '0235+153',
 '0235+164',
 '0235+205',
 '0235-266',
 '0235-618',
 '0236+420',
 '0237+040',
 '0237+185',
 '0237-027',
 '0237-233',
 '0238+711',
 '0238-052',
 '0239+108',
 '0239+175',
 '0240+110',
 '0240-060',
 '0240-217',
 '0241+622',
 '0241-564',
 '0242+131',
 '0242+161',
 '0242+238',
 '0242-113',
 '0243+339',
 '0243+354',
 '0244+327',
 '0244-128',
 '0244-297',
 '0244-452',
 '0244-470',
 '0245+043',
 '0245-167',
 '0246+061',
 '0247+16A',
 '0248+373',
 '0248+430',
 '0248+560',
 '0248-266',
 '0249+171',
 '0249+383',
 '0250+178',
 '0250+320',
 '0250+508',
 '0250-001',
 '0250-122',
 '0250-225',
 '0251+235',
 '0251+393',
 '0251+785',
 '0252+657',
 '0252+818',
 '0252-549',
 '0252-712',
 '0253+133',
 '0253-218',
 '0254+155',
 '0254+185',
 '0254+434',
 '0254-334',
 '0255+288',
 '0255-124',
 '0256+054',
 '0256+075',
 '0256+115',
 '0256+148',
 '0256+192',
 '0256+423',
 '0256-005',
 '0256-256',
 '0256-393',
 '0257-057',
 '0258+011',
 '0258+058',
 '0258+533',
 '0258+772',
 '0258+818',
 '0258-163',
 '0258-170',
 '0258-184',
 '0258-344',
 '0259+121',
 '0259+203',
 '0259+681',
 '0259-316',
 '0300+129',
 '0300+470',
 '0301+336',
 '0301-243',
 '0302+173',
 '0302+625',
 '0302-437',
 '0302-623',
 '0303+051',
 '0303+130',
 '0303+697',
 '0303-245',
 '0304+124',
 '0305+237',
 '0305-491',
 '0306+102',
 '0306+274',
 '0306-061',
 '0307+178',
 '0307+380',
 '0307-085',
 '0307-362',
 '0308-611',
 '0309+360',
 '0309+411',
 '0310+013',
 '0310+022',
 '0310+410',
 '0312+100',
 '0312-770',
 '0313+273',
 '0313-020',
 '0313-171',
 '0314+565',
 '0314+696',
 '0315+291',
 '0315+389',
 '0315-006',
 '0315-282',
 '0316+159',
 '0316+308',
 '0316-164',
 '0316-444',
 '0317+188',
 '0317+659',
 '0318+438',
 '0318-172',
 '0318-388',
 '0319+121',
 '0319+177',
 '0319+396',
 '0319-056',
 '0319-133',
 '0319-315',
 '0320+015',
 '0320+045',
 '0320+218',
 '0321+340',
 '0321+467',
 '0322+222',
 '0322+230',
 '0322-230',
 '0322-294',
 '0323+151',
 '0323-244',
 '0324-328',
 '0324-379',
 '0325+005',
 '0325+256',
 '0325+395',
 '0325-182',
 '0325-222',
 '0326+278',
 '0326+349',
 '0327+364',
 '0327+467',
 '0327-241',
 '0328+238',
 '0328+677',
 '0328-060',
 '0329+174',
 '0329+232',
 '0329+654',
 '0329-110',
 '0329-255',
 '0329-404',
 '0330+148',
 '0331+022',
 '0332+078',
 '0332-375',
 '0332-403',
 '0333+224',
 '0333-073',
 '0334+014',
 '0334+309',
 '0334-131',
 '0334-207',
 '0334-546',
 '0335+225',
 '0335+599',
 '0335-122',
 '0335-364',
 '0336+133',
 '0336+473',
 '0336+539',
 '0336-017',
 '0337+337',
 '0338+388',
 '0338+480',
 '0338-030',
 '0338-214',
 '0339+131',
 '0339+651',
 '0339+683',
 '0340+362',
 '0340-140',
 '0340-302',
 '0340-330',
 '0341+065',
 '0341+158',
 '0341+729',
 '0341-256',
 '0342+147',
 '0342+538',
 '0343+485',
 '0344+199',
 '0344+235',
 '0344+558',
 '0345+085',
 '0345+416',
 '0345+460',
 '0346+209',
 '0346+242',
 '0346+514',
 '0346+800',
 '0346-163',
 '0346-279',
 '0347+288',
 '0347-211',
 '0348+049',
 '0348-031',
 '0348-120',
 '0348-326',
 '0349+662',
 '0350+177',
 '0350+465',
 '0350-253',
 '0351+045',
 '0351+390',
 '0352+123',
 '0352+199',
 '0352+210',
 '0352+605',
 '0352+825',
 '0352-164',
 '0353+206',
 '0353+289',
 '0354+000',
 '0354+231',
 '0354+559',
 '0354+599',
 '0354-405',
 '0355+055',
 '0355-079',
 '0355-483',
 '0355-669',
 '0356+157',
 '0356+278',
 '0356+322',
 '0356-033',
 '0357+057',
 '0357-263',
 '0358+031',
 '0358+040',
 '0358+210',
 '0358-162',
 '0359-151',
 '0359-294',
 '0400+258',
 '0400-319',
 '0401+820',
 '0401-248',
 '0402+160',
 '0402+379',
 '0402+682',
 '0402-362',
 '0403+064',
 '0403+208',
 '0403+768',
 '0403-132',
 '0403-179',
 '0404+065',
 '0404+075',
 '0404+169',
 '0404-240',
 '0405+305',
 '0405-015',
 '0405-123',
 '0405-331',
 '0405-385',
 '0406+065',
 '0406+121',
 '0406-056',
 '0406-127',
 '0407-170',
 '0407-199',
 '0407-658',
 '0408+085',
 '0408+171',
 '0409+000',
 '0409+045',
 '0409+188',
 '0409+229',
 '0409+527',
 '0409-045',
 '0409-280',
 '0410+110',
 '0410+168',
 '0410+200',
 '0411+054',
 '0411+245',
 '0411+341',
 '0411-063',
 '0412+254',
 '0412+256',
 '0412+447',
 '0413-136',
 '0413-210',
 '0414+548',
 '0414-157',
 '0414-189',
 '0414-253',
 '0414-337',
 '0414-341',
 '0415+211',
 '0415+379',
 '0415+398',
 '0415+572',
 '0416+184',
 '0416-216',
 '0417-302',
 '0418+259',
 '0418+437',
 '0418+532',
 '0418-151',
 '0419+175',
 '0419+308',
 '0419-068',
 '0420+022',
 '0420+210',
 '0420+417',
 '0420-014',
 '0420-206',
 '0421+019',
 '0421+023',
 '0421+145',
 '0421+464',
 '0421+683',
 '0422+004',
 '0422+079',
 '0422+224',
 '0422-380',
 '0422-389',
 '0423+051',
 '0423+183',
 '0423+186',
 '0423+233',
 '0423+237',
 '0423+297',
 '0423-163',
 '0424+128',
 '0424+328',
 '0424+414',
 '0424+670',
 '0424-131',
 '0425+048',
 '0425+174',
 '0425-071',
 '0426+181',
 '0426+273',
 '0426+332',
 '0426-126',
 '0426-380',
 '0427+168',
 '0427+235',
 '0427-055',
 '0427-230',
 '0427-502',
 '0428+172',
 '0428+205',
 '0428+314',
 '0428-042',
 '0428-252',
 '0429+174',
 '0429+448',
 '0430+289',
 '0430-163',
 '0430-332',
 '0431-512',
 '0432+246',
 '0432+254',
 '0432-148',
 '0432-253',
 '0432-606',
 '0433+295',
 '0433-101',
 '0433-422',
 '0434+212',
 '0434+299',
 '0434-188',
 '0434-240',
 '0435+217',
 '0435+487',
 '0435-300',
 '0436+052',
 ...]

In [19]:
sourcedata['1803+784']

KeyError: '1803+784'

In [20]:
sourcedata[ '0003+380']

,SOU_LCO,DATETIME,EPOCH,RA,RA ERR,DEC,DEC ERR,CORR,OBS
153,0003+380,94JUL20XN,1994.55259,00_05_57.17543950,0.9819,+38_20_15.1470266,0.9488,-0.0821,18.0 / 28.0
154,0003+380,96JUN07XV,1996.43623,00_05_57.17536678,0.3306,+38_20_15.1498482,0.3165,-0.2283,87.0 / 87.0
155,0003+380,96OCT22XE,1996.81109,00_05_57.17540129,0.2666,+38_20_15.1489784,0.2489,-0.2412,39.0 / 43.0
156,0003+380,97JAN11XV,1997.03171,00_05_57.17539314,0.2032,+38_20_15.1488451,0.1825,-0.1135,157.0 / 161.0
157,0003+380,98JUN24XA,1998.48138,00_05_57.17532608,0.2599,+38_20_15.1513539,0.1995,0.4015,569.0 / 585.0
158,0003+380,98JUL21XE,1998.55510,00_05_57.17544123,0.6762,+38_20_15.1486102,0.4560,-0.2618,10.0 / 17.0
159,0003+380,99APR20XE,1999.30253,00_05_57.17531391,1.2156,+38_20_15.1486235,0.6161,-0.5439,3.0 / 7.0
160,0003+380,99OCT26XE,1999.81999,00_05_57.17550252,0.5785,+38_20_15.1486978,0.6144,-0.2046,9.0 / 10.0
161,0003+380,00AUG17XN,2000.63038,00_05_57.17534916,0.7534,+38_20_15.1494639,0.6266,-0.3564,22.0 / 31.0
162,0003+380,01MAY18XN,2001.38010,00_05_57.17619255,4.0039,+38_20_15.1481247,5.9287,0.1596,5.0 / 9.0
163,0003+380,01JUN06XN,2001.43281,00_05_57.17523407,1.6059,+38_20_15.1489368,1.5500,-0.1793,7.0 / 9.0
164,0003+380,01DEC10XN,2001.94434,00_05_57.17538703,1.0068,+38_20_15.1473473,1.0596,0.0005,8.0 / 9.0
165,0003+380,04FEB02XA,2004.09091,00_05_57.17540155,0.3204,+38_20_15.1488820,0.4126,0.1835,57.0 / 64.0
166,0003+380,04FEB09XA,2004.11008,00_05_57.17542823,0.2315,+38_20_15.1489883,0.2236,0.1087,46.0 / 59.0
167,0003+380,05JAN03XA,2005.01083,00_05_57.17537059,0.4285,+38_20_15.1492885,0.3488,0.0398,27.0 / 32.0
168,0003+380,05JAN10XA,2005.03000,00_05_57.17533946,0.3749,+38_20_15.1489938,0.3534,0.0066,14.0 / 14.0
169,0003+380,05DEC12XA,2005.94991,00_05_57.17548363,0.6472,+38_20_15.1497055,0.5742,-0.1498,8.0 / 12.0
170,0003+380,05DEC14XA,2005.95551,00_05_57.17537878,0.1389,+38_20_15.1493702,0.1534,0.1710,98.0 / 114.0
171,0003+380,06NOV13XA,2006.86983,00_05_57.17544702,0.3142,+38_20_15.1492991,0.2894,0.2315,24.0 / 27.0
172,0003+380,07JAN29XA,2007.08065,00_05_57.17550416,1.1661,+38_20_15.1490108,0.2603,0.1489,15.0 / 15.0
173,0003+380,07MAR27XA,2007.23677,00_05_57.17541834,0.1466,+38_20_15.1488278,0.1668,0.0665,165.0 / 213.0
174,0003+380,08JUN02XA,2008.42220,00_05_57.17537460,0.1399,+38_20_15.1488581,0.1769,-0.1104,37.0 / 41.0
175,0003+380,08AUG04XA,2008.59468,00_05_57.17538479,1.0353,+38_20_15.1492061,0.3142,0.2887,23.0 / 26.0
176,0003+380,08SEP02XA,2008.67408,00_05_57.17533809,0.4037,+38_20_15.1489119,0.2768,0.1440,40.0 / 45.0
177,0003+380,08SEP08XA,2008.69051,00_05_57.17539135,0.1551,+38_20_15.1489714,0.1901,0.0612,37.0 / 40.0
178,0003+380,09MAY13XA,2009.36687,00_05_57.17520138,0.3810,+38_20_15.1500651,0.2256,-0.6447,239.0 / 244.0
179,0003+380,09AUG10XA,2009.61042,00_05_57.17536405,0.5858,+38_20_15.1484231,0.4935,-0.0892,19.0 / 23.0
180,0003+380,15MAR21XA,2015.21834,00_05_57.17605044,1.4409,+38_20_15.1061716,7.3239,-0.7252,3.0 / 11.0
181,0003+380,18JUL05XC,2018.51068,00_05_57.17538496,0.2022,+38_20_15.1519252,0.2089,-0.1925,93.0 / 100.0

In [21]:
len(sourcelist)

1083