In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [2]:
def load_data(data_txt):
    cols = ['MJD','R.A. (mas)', 'Dec. (mas)', 'Err. R.A. (mas)', 'Err. Dec. (mas)', 'Corr.', 'Del.']
    cols_widths = [(1,9),(10,26),(27,46),(47,56),(57,66),(67,74),(75,79)]
    df = pd.read_fwf(data_txt, colspecs=cols_widths, skiprows=4, header=None, names=cols)    
    return df

In [3]:
df_18 = load_data('1803+784_dem.txt')
df_18

,MJD,R.A. (mas),Dec. (mas),Err. R.A. (mas),Err. Dec. (mas),Corr.,Del.
0,5754.258,-1.90962518674,-1.887001224077,1.2912,0.7417,-0.084,40.0
1,5759.251,-1.55435928306,-2.305601981334,1.2032,1.1362,0.028,19.0
2,5764.244,0.05103953497,1.460397601249,0.7069,0.6182,0.325,21.0
3,5769.259,-5.73853182778,0.890999990588,2.5316,1.1073,-0.363,25.0
4,5864.264,-2.97200423879,0.696600000083,0.6484,0.6307,0.547,27.0
...,...,...,...,...,...,...,...
2724,181.271,-0.60755307093,-0.275702404906,0.2258,0.2346,0.037,65.0
2725,188.269,0.01538376099,0.475898411878,0.1854,0.1910,0.278,107.0
2726,195.271,0.06645352894,0.082897196307,0.1307,0.1282,0.102,201.0
2727,202.270,-1.38717685892,-4.237200005264,0.1272,0.1330,0.139,98.0
2728,208.271,-0.03085748453,0.025297191542,0.1527,0.1679,0.070,89.0

In [4]:
df_18.dtypes

MJD                float64
R.A. (mas)          object
Dec. (mas)          object
Err. R.A. (mas)    float64
Err. Dec. (mas)    float64
Corr.              float64
Del.               float64
dtype: object

In [5]:
df_16 = load_data('1611+343_dem.txt')
df_16

,MJD,R.A. (mas),Dec. (mas),Err. R.A. (mas),Err. Dec. (mas),Corr.,Del.
0,7165.332,1.472509,4.937699,0.5046,1.0159,-0.003,21
1,7610.794,47.422934,7.737098,3.1809,1.6415,0.835,3
2,7620.338,0.554842,-0.460800,1.0507,1.1907,-0.022,11
3,7640.018,243.542066,-967.786099,6.7731,6.0100,-0.593,3
4,7655.329,2.151144,2.641702,0.7536,0.9041,0.061,20
...,...,...,...,...,...,...,...
2045,9346.229,-0.512792,-1.148699,0.2870,0.3626,0.093,49
2046,9348.271,-1.160294,-0.345802,0.1943,0.2444,0.385,78
2047,9374.251,-1.077559,2.305400,0.3242,0.7562,-0.161,13
2048,9430.248,0.144135,-0.896602,0.3406,0.7687,-0.240,12
2049,9507.228,0.083231,-1.484798,0.1257,0.1132,0.313,121

In [6]:
df_16.dtypes

MJD                float64
R.A. (mas)         float64
Dec. (mas)         float64
Err. R.A. (mas)    float64
Err. Dec. (mas)    float64
Corr.              float64
Del.                 int64
dtype: object

In [7]:
for col in df_18.columns:
    if df_18[col].dtype == 'object':
        try:
            df_18[col] = df_18[col].astype(float)
        except ValueError as e:
            print(f"{e}")

could not convert string to float: '****************'
could not convert string to float: '1.7757972127.96'

In [23]:
def convert_value(value):
    try:
        return float(value)
    except ValueError:
        return None

In [43]:
def preprocess_data(df):
    df_new = df.apply(pd.to_numeric, errors='coerce').dropna()
            
    return df_new

In [44]:
df_18_new = preprocess_data(df_18)
df_18_new.dtypes

MJD                float64
R.A. (mas)         float64
Dec. (mas)         float64
Err. R.A. (mas)    float64
Err. Dec. (mas)    float64
Corr.              float64
Del.               float64
dtype: object

In [45]:
len(df_18_new)

2727

In [46]:
df_16_new = preprocess_data(df_16)
df_16_new.dtypes

MJD                float64
R.A. (mas)         float64
Dec. (mas)         float64
Err. R.A. (mas)    float64
Err. Dec. (mas)    float64
Corr.              float64
Del.                 int64
dtype: object