In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [14]:
def load_data(data_txt):
    cols = ['MJD','R.A. (mas)', 'Dec. (mas)', 'Err. R.A. (mas)', 'Err. Dec. (mas)', 'Corr.', 'Del.']
    cols_widths = [(1,9),(10,26),(27,46),(47,56),(57,66),(67,74),(75,79)]
    df = pd.read_fwf(data_txt, colspecs=cols_widths, skiprows=4, header=None, names=cols)    
    return df

In [15]:
df_18 = load_data('1803+784_dem.txt')
df_18

,MJD,R.A. (mas),Dec. (mas),Err. R.A. (mas),Err. Dec. (mas),Corr.,Del.
0,5754.258,-1.90962518674,-1.887001224077,1.2912,0.7417,-0.084,40.0
1,5759.251,-1.55435928306,-2.305601981334,1.2032,1.1362,0.028,19.0
2,5764.244,0.05103953497,1.460397601249,0.7069,0.6182,0.325,21.0
3,5769.259,-5.73853182778,0.890999990588,2.5316,1.1073,-0.363,25.0
4,5864.264,-2.97200423879,0.696600000083,0.6484,0.6307,0.547,27.0
...,...,...,...,...,...,...,...
2724,181.271,-0.60755307093,-0.275702404906,0.2258,0.2346,0.037,65.0
2725,188.269,0.01538376099,0.475898411878,0.1854,0.1910,0.278,107.0
2726,195.271,0.06645352894,0.082897196307,0.1307,0.1282,0.102,201.0
2727,202.270,-1.38717685892,-4.237200005264,0.1272,0.1330,0.139,98.0
2728,208.271,-0.03085748453,0.025297191542,0.1527,0.1679,0.070,89.0

In [16]:
df_18.dtypes

MJD                float64
R.A. (mas)          object
Dec. (mas)          object
Err. R.A. (mas)    float64
Err. Dec. (mas)    float64
Corr.              float64
Del.               float64
dtype: object

In [17]:
df_16 = load_data('1611+343_dem.txt')
df_16

,MJD,R.A. (mas),Dec. (mas),Err. R.A. (mas),Err. Dec. (mas),Corr.,Del.
0,7165.332,1.472509,4.937699,0.5046,1.0159,-0.003,21
1,7610.794,47.422934,7.737098,3.1809,1.6415,0.835,3
2,7620.338,0.554842,-0.460800,1.0507,1.1907,-0.022,11
3,7640.018,243.542066,-967.786099,6.7731,6.0100,-0.593,3
4,7655.329,2.151144,2.641702,0.7536,0.9041,0.061,20
...,...,...,...,...,...,...,...
2045,9346.229,-0.512792,-1.148699,0.2870,0.3626,0.093,49
2046,9348.271,-1.160294,-0.345802,0.1943,0.2444,0.385,78
2047,9374.251,-1.077559,2.305400,0.3242,0.7562,-0.161,13
2048,9430.248,0.144135,-0.896602,0.3406,0.7687,-0.240,12
2049,9507.228,0.083231,-1.484798,0.1257,0.1132,0.313,121

In [18]:
df_16.dtypes

MJD                float64
R.A. (mas)         float64
Dec. (mas)         float64
Err. R.A. (mas)    float64
Err. Dec. (mas)    float64
Corr.              float64
Del.                 int64
dtype: object

In [19]:
def preprocess_data(df):
    df_new = df.apply(pd.to_numeric, errors='coerce').dropna()
            
    return df_new

In [20]:
df_18_new = preprocess_data(df_18)
df_18_new.dtypes

MJD                float64
R.A. (mas)         float64
Dec. (mas)         float64
Err. R.A. (mas)    float64
Err. Dec. (mas)    float64
Corr.              float64
Del.               float64
dtype: object

In [21]:
len(df_18_new)

2727

In [22]:
df_16_new = preprocess_data(df_16)
df_16_new.dtypes

MJD                float64
R.A. (mas)         float64
Dec. (mas)         float64
Err. R.A. (mas)    float64
Err. Dec. (mas)    float64
Corr.              float64
Del.                 int64
dtype: object

In [23]:
len(df_16_new)

2050

In [24]:
def process_data(data_txt):
    cols = ['MJD','R.A. (mas)', 'Dec. (mas)', 'Err. R.A. (mas)', 'Err. Dec. (mas)', 'Corr.', 'Del.']
    cols_widths = [(1,9),(10,26),(27,46),(47,56),(57,66),(67,74),(75,79)]
    df = pd.read_fwf(data_txt, colspecs=cols_widths, skiprows=4, header=None, names=cols)    
    df_new = df.apply(pd.to_numeric, errors='coerce').dropna()    
    return df_new

In [26]:
process_data('1803+784_dem.txt')

,MJD,R.A. (mas),Dec. (mas),Err. R.A. (mas),Err. Dec. (mas),Corr.,Del.
0,5754.258,-1.909625,-1.887001,1.2912,0.7417,-0.084,40.0
1,5759.251,-1.554359,-2.305602,1.2032,1.1362,0.028,19.0
2,5764.244,0.051040,1.460398,0.7069,0.6182,0.325,21.0
3,5769.259,-5.738532,0.891000,2.5316,1.1073,-0.363,25.0
4,5864.264,-2.972004,0.696600,0.6484,0.6307,0.547,27.0
...,...,...,...,...,...,...,...
2724,181.271,-0.607553,-0.275702,0.2258,0.2346,0.037,65.0
2725,188.269,0.015384,0.475898,0.1854,0.1910,0.278,107.0
2726,195.271,0.066454,0.082897,0.1307,0.1282,0.102,201.0
2727,202.270,-1.387177,-4.237200,0.1272,0.1330,0.139,98.0
2728,208.271,-0.030857,0.025297,0.1527,0.1679,0.070,89.0

In [32]:
process_data('ICRF3 Dem/series_ind_dem/1803+784_dem.txt')

,MJD,R.A. (mas),Dec. (mas),Err. R.A. (mas),Err. Dec. (mas),Corr.,Del.
0,5754.258,-1.910705,-1.887599,1.2912,0.7417,-0.084,40
1,5759.251,-1.555439,-2.306200,1.2032,1.1362,0.028,19
2,5764.244,0.049960,1.459800,0.7069,0.6182,0.325,21
3,5769.259,-5.739611,0.890402,2.5316,1.1073,-0.363,25
4,5864.264,-2.973084,0.696002,0.6484,0.6307,0.547,27
...,...,...,...,...,...,...,...
2728,208.271,-0.031937,0.024700,0.1527,0.1679,0.070,89
2729,223.271,0.037455,-0.073901,0.1566,0.1349,-0.046,123
2730,230.270,0.184486,0.078800,0.1138,0.1303,0.272,93
2731,237.271,-0.296250,0.427201,0.1807,0.1814,0.002,82
2732,241.209,0.030198,0.267800,0.1769,0.2271,0.068,299

In [33]:
load_data('ICRF3 Dem/series_ind_dem/1803+784_dem.txt')

,MJD,R.A. (mas),Dec. (mas),Err. R.A. (mas),Err. Dec. (mas),Corr.,Del.
0,5754.258,-1.91070473740,-1.887598813255,1.2912,0.7417,-0.084,40
1,5759.251,-1.55543883372,-2.306199570512,1.2032,1.1362,0.028,19
2,5764.244,0.04995998428,1.459800012071,0.7069,0.6182,0.325,21
3,5769.259,-5.73961137839,0.890402401410,2.5316,1.1073,-0.363,25
4,5864.264,-2.97308378943,0.696002410905,0.6484,0.6307,0.547,27
...,...,...,...,...,...,...,...
2728,208.271,-0.03193703522,0.024699602363,0.1527,0.1679,0.070,89
2729,223.271,0.03745506604,-0.073900770303,0.1566,0.1349,-0.046,123
2730,230.270,0.18448567272,0.078800428582,0.1138,0.1303,0.272,93
2731,237.271,-0.29624981133,0.427201212005,0.1807,0.1814,0.002,82
2732,241.209,0.03019825004,0.267800425036,0.1769,0.2271,0.068,299